services:
  db:
    image: mariadb:10.6
    container_name: nc-dev-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: devroot
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - db:/var/lib/mysql

  app:
    image: nextcloud:28
    container_name: nc-dev-app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 192.168.1.5
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=512M
    volumes:
      - nextcloud:/var/www/html

  redis:
    image: redis:alpine
    container_name: nc-dev-redis
    restart: unless-stopped

  cron:
    image: nextcloud:28
    container_name: nc-dev-cron
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
